name: flutter_base_project
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  flutter: 3.7.10
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  shared_preferences: ^2.3.2
  url_launcher: ^6.3.0


  # Network
  http: ^1.2.2
  connectivity: ^3.0.6
  webview_flutter: ^4.8.0
  android_id: ^0.4.0

  # UI
  cupertino_icons: ^1.0.8
  flutter_svg: ^2.0.10+1
  flutter_local_notifications: ^17.2.2
  banner_image: ^1.0.7
  overlay_kit: ^1.0.8


  # State manager
  get: ^4.6.6

  # Error handler
  dop_logger:
    git:
      url: https://github.com/dophub/applogger.git
      ref: prod-0801

dev_dependencies:
  flutter_lints: any
  build_runner:
  flutter_gen_runner:

dependency_overrides:

flutter_gen:
  output: lib/app/constants/assets
  line_length: 120

  integrations:
    flutter_svg: true
  fonts:
    enabled: false

flutter:
  uses-material-design: true
  assets:
    #- assets/other/


  fonts:
    - family: GreycliffCF
      fonts:
        - asset: assets/fonts/GreycliffCF-Light.ttf
          weight: 300
        - asset: assets/fonts/GreycliffCF-Regular.ttf
          weight: 400
        - asset: assets/fonts/GreycliffCF-Medium.ttf
          weight: 500
        - asset: assets/fonts/GreycliffCF-DemiBold.ttf
          weight: 600
        - asset: assets/fonts/GreycliffCF-Bold.ttf
          weight: 700